Update MONGO_ACCOUNTING_DATABASE_URI in .env.sampl
codex-team/codex-accounting pull request #33
Opened 2020-12-02 05:05 UTC by ranemihir

Changing `localhost` to `mongodb`. The mongo

2020-12-02 05:26 UTC, nikmel2803 approved these changes

2020-12-02 18:07 UTC, neSpecc requested changes

2020-12-02 18:07 UTC, neSpecc commented on .env.sample
> +MONGO_ACCOUNTING_DATABASE_URI=mongodb://mongodb:27017/codex_accounting
```suggestion
# for running via mono repository
MONGO_ACCOUNTING_DATABASE_URI=mongodb://mongodb:27017/codex_accounting
# for running as standalone
# MONGO_ACCOUNTING_DATABASE_URI=mongodb://localhost:27017/codex_accounting
```

2020-12-07 16:12 UTC, neSpecc approved these changes

2020-12-07 16:13 UTC, neSpecc commented
@ranemihir merge please

2020-12-07 16:40 UTC, ranemihir commented
@neSpecc I dont think I have the permissions.

2020-12-07 16:53 UTC, merged